[common]
main_mode = 1
source_folder = "./"
failed_output_folder = "failed"
success_output_folder = "./"
link_mode = 0
scan_hardlink = false
failed_move = false
auto_exit = false
multi_threading = false
actor_gender = "female"
del_empty_folder = false
nfo_skip_days = 30
ignore_failed_list = false
download_only_missing_images = true
mapping_table_validity = 7
jellyfin = false
actor_only_tag = false
sleep = 3

# 剧照
[extrafanart]
switch = true
extrafanart_folder = "extrafanart"

[proxy]
switch = true
proxy = "socks5://127.0.0.1:10808"
timeout = 20
retry = 3
cacert_file = ""

[debug_mode]
switch = false

[name_rule]
location_rule = 'actor+"/"+number'
naming_rule = 'number+"-"+title'
max_title_len = 50
image_naming_with_number = false

[uncensored]
uncensored_prefix = "PT-,S2M,BT,LAF,SMD,SMBD,SM3D2DBD,SKY-,SKYHD,CWP,CWDV,CWBD,CW3D2DBD,MKD,MKBD,MXBD,MK3D2DBD,MCB3DBD,MCBD,RHJ,MMDV"

[translate]
switch = false
engine = "azure"
service_url = "https://api.cognitive.microsofttranslator.com/translate?api-version=3.0"
access_key = ""
region = "japaneast"
values = "outline"

[priority]
website = "fanza,javbus,airav,jav321,xcity,mgstage,fc2,avsox,dlsite,carib,madou,mv91,getchu,javdb,gcolle"

[sources.fanza]
name = "fanza"
age_check = { url = "https://www.dmm.co.jp/age_check/=/declared=yes/", target_name = "rurl" }
detail_url = ["https://www.dmm.co.jp/mono/dvd/-/detail/=/cid="]
expr_number = "//td[contains(text(),'品番：')]/following-sibling::td/text()"
expr_title = "//*[starts-with(@id, 'title')]/text()"
expr_actor_name = '//td[contains(text(),"出演者")]/following-sibling::td/span/a/text()'
expr_actor_photo = ''
expr_studio = "//td[contains(text(),'メーカー')]/following-sibling::td/text()"
expr_runtime = "//td[contains(text(),'収録時間')]/following-sibling::td/text()"
expr_release = "//td[contains(text(),'発売日：')]/following-sibling::td/text()"
expr_outline = "//div[@class='mg-b20 lh4']//p/text()"
expr_director = "//td[contains(text(),'監督：')]/following-sibling::td/text()"
expr_tags = "//td[contains(text(),'ジャンル：')]/following-sibling::td/a/text()"
expr_label = "//td[contains(text(),'レーベル：')]/following-sibling::td/a/text()"
expr_series = "//td[contains(text(),'シリーズ：')]/following-sibling::td/a/text()"
expr_cover = '//a[@id="$cover_number"]/@href'
expr_small_cover = '//a[@id="$cover_number"]/img/@src'
expr_extrafanart = '//a[@name="sample-image"]/img/@src'
expr_trailer = ""
expr_uncensored = ""
expr_uservotes = ""
expr_userrating = ""


