[proxy]
switch = true
proxy = "socks5://127.0.0.1:10808"
timeout = 20
retry = 3
cacert_file = ""

[translate]
switch = true
service_url = ""
access_key = ""
region = ""

[sources.fanza]
name = "fanza"
detail_url = [""]
expr_number = ""
expr_title = ""
expr_studio = ""
expr_runtime = ""
expr_release = ""
expr_outline = ""
expr_director = ""
expr_actor = ""
expr_tags = ""
expr_label = ""
expr_series = ""
expr_cover =""
expr_smallcover = ""
expr_extrafanart = ""
expr_trailer = ""
expr_actorphoto = ""
expr_uncensored = ""
expr_uservotes = ""
expr_userrating = ""


