[common]
# 1-正常模式，2-整理模式，3-更瓣元数据
main_mode = 1
source_folder = "./"
failed_output_folder = "failed"
success_output_folder = "./"
parser_folder = "./parser"
link_mode = 0
scan_hardlink = false
failed_move = false
auto_exit = false
actor_gender = "female"
del_empty_folder = true
ignore_failed_list = false
download_only_missing_images = true
sleep = 3

# 剧照
[extra_fanart]
switch = true
extra_fanart_folder = "extrafanart"

[face]
locations_model = "hog"
aspect_ratio = 2.12

[proxy]
switch = true
proxy = "http://127.0.0.1:10809"
timeout = 20
retry = 3
cacert_file = ""

[debug_mode]
switch = true

[name_rule]
location_rule = '$actor/$number'
naming_rule = '$number-$title'
max_title_len = 50
image_naming_with_number = false

[uncensored]
uncensored_prefix = "PT-,S2M,BT,LAF,SMD,SMBD,SM3D2DBD,SKY-,SKYHD,CWP,CWDV,CWBD,CW3D2DBD,MKD,MKBD,MXBD,MK3D2DBD,MCB3DBD,MCBD,RHJ,MMDV"

[media]
# 影片后缀
media_type = ".mp4,.avi,.rmvb,.wmv,.mov,.mkv,.flv,.ts,.webm,.iso,.mpg,.m4v"
# 字幕后缀
sub_type = ".smi,.srt,.idx,.sub,.sup,.psb,.ssa,.ass,.usf,.xss,.ssf,.rt,.lrc,.sbv,.vtt,.ttml"

[translate]
switch = false
engine = "azure"
service_url = "https://api.cognitive.microsofttranslator.com/translate?api-version=3.0"
access_key = ""
region = "japaneast"
values = "outline"

[[number_extractor]]
name = "rebd"
regex = '(?i)\b(h_346)?REBD-?\d+'
sources = ["fanza", "javbus", "javdb"]
[[number_extractor]]
name = "oae"
regex = '(?i)\bOAE-?\d+'
sources = ["fanza", "javbus", "javdb"]
[[number_extractor]]
name = "sprl"
regex = '(?i)\bSPRL-?\d+'
sources = ["fanza", "javbus", "javdb"]
[[number_extractor]]
name = "higr"
regex = '(?i)\bHIGR-?\d+'
sources = ["fanza", "javbus", "javdb"]
[[number_extractor]]
name = "mmnd"
regex = '(?i)\bMMND-?\d+'
sources = ["fanza", "javbus", "javdb"]
[[number_extractor]]
name = "impno"
regex = '(?i)\bIMPNO-?\d+'
sources = ["javdb", "javbus"]
[[number_extractor]]
name = "mbdd"
regex = '(?i)\bMBDD-?\d+'
sources = ["javbus", "javdb"]
[[number_extractor]]
name = "fc2"
regex = '(?i)\bFC2-?(PPV[-\s])?\d+'
sources = ["fc2", "nanojav", "missav"]
[[number_extractor]]
name = "heyzo"
regex = '(?i)\bheyzo[-\s]+\d+'
sources = ["javbus", "javdb"]
[[number_extractor]]
name = "carib"
regex = '\d{6}(-|_)\d{3}'
sources = ["carib"]
[[number_extractor]]
name = "H4610"
regex = 'H4610(-|_)\w+'
sources = ["H4610"]
[[number_extractor]]
name = "heydouga"
regex = '\d{4}(-|_)\d{4}'
sources = ["heydouga"]
[[number_extractor]]
name = "kin8"
regex = '(?i)\bkin8-?\d+'
sources = ["kin8"]
[[number_extractor]]
name = "msfh"
regex = '(?i)\bMSFH-?\d+'
sources = ["nanojav"]
[[number_extractor]]
name = "ss"
regex = '(?i)\SS-?\d+'
sources = ["fanza"]
