[proxy]
switch = true
proxy = "socks5://127.0.0.1:10808"
timeout = 20
retry = 3
cacert_file = ""

[translate]
switch = true
service_url = ""
access_key = ""
region = ""

[sources.fanza]
name = "fanza"
age_check = { url = "https://www.dmm.co.jp/age_check/=/declared=yes/", target_name = "rurl" }
detail_url = ["https://www.dmm.co.jp/mono/dvd/-/detail/=/cid="]
expr_number = "//td[contains(text(),'品番：')]/following-sibling::td/text()"
expr_title = "//*[starts-with(@id, 'title')]/text()"
expr_studio = "//td[contains(text(),'メーカー')]/following-sibling::td/text()"
expr_runtime = "//td[contains(text(),'収録時間')]/following-sibling::td/text()"
expr_release = "//td[contains(text(),'発売日：')]/following-sibling::td/text()"
expr_outline = "//div[@class='mg-b20 lh4']//p/text()"
expr_director = "//td[contains(text(),'監督：')]/following-sibling::td/text()"
expr_actor = "//td[contains(text(),'出演者')]/following-sibling::td/span/a/text()"
expr_tags = "//td[contains(text(),'ジャンル：')]/following-sibling::td/a/text()"
expr_label = "//td[contains(text(),'レーベル：')]/following-sibling::td/a/text()"
expr_series = "//td[contains(text(),'シリーズ：')]/following-sibling::td/a/text()"
expr_cover = '//a[@id="$cover_number"]/@href'
expr_small_cover = ""
expr_extrafanart = '//a[@name="sample-image"]/img/@src'
expr_trailer = ""
expr_actorphoto = ""
expr_uncensored = ""
expr_uservotes = ""
expr_userrating = ""


