[common]
# 1-正常模式，2-整理模式，3-更瓣元数据
main_mode = 1
source_folder = "./"
failed_output_folder = "failed"
success_output_folder = "./"
link_mode = 0
scan_hardlink = false
failed_move = false
auto_exit = false
actor_gender = "female"
del_empty_folder = true
ignore_failed_list = false
download_only_missing_images = true
sleep = 3

# 剧照
[extra_fanart]
switch = true
extra_fanart_folder = "extrafanart"

[face]
locations_model = "hog"
aspect_ratio = 2.12

[proxy]
switch = true
proxy = "socks5://127.0.0.1:10808"
timeout = 20
retry = 3
cacert_file = ""

[debug_mode]
switch = true

[name_rule]
location_rule = '$actor/$number'
naming_rule = '$number-$title'
max_title_len = 50
image_naming_with_number = false

[uncensored]
uncensored_prefix = "PT-,S2M,BT,LAF,SMD,SMBD,SM3D2DBD,SKY-,SKYHD,CWP,CWDV,CWBD,CW3D2DBD,MKD,MKBD,MXBD,MK3D2DBD,MCB3DBD,MCBD,RHJ,MMDV"

[media]
# 影片后缀
media_type = ".mp4,.avi,.rmvb,.wmv,.mov,.mkv,.flv,.ts,.webm,.iso,.mpg,.m4v"
# 字幕后缀
sub_type = ".smi,.srt,.idx,.sub,.sup,.psb,.ssa,.ass,.usf,.xss,.ssf,.rt,.lrc,.sbv,.vtt,.ttml"

[translate]
switch = false
engine = "azure"
service_url = "https://api.cognitive.microsofttranslator.com/translate?api-version=3.0"
access_key = ""
region = "japaneast"
values = "outline"

[[number_extractor]]
name = "rebd"
regex = '(?i)\b(h_346)?REBD-?\d+'
[[number_extractor]]
name = "oae"
regex = '(?i)\bOAE-?\d+'
[[number_extractor]]
name = "sprl"
regex = '(?i)\bSPRL-?\d+'
[[number_extractor]]
name = "higr"
regex = '(?i)\bHIGR-?\d+'
[[number_extractor]]
name = "fc2"
regex = '(?i)\bFC2-?(PPV[-\s])?\d+'
[[number_extractor]]
name = "heyzo"
regex = '(?i)\bheyzo[-\s]+\d+'
[[number_extractor]]
name = "carib"
regex = '\d{6}(-|_)\d{3}'
[[number_extractor]]
name = "H4610"
regex = 'H4610(-|_)\w+'

[sources.fanza]
name = "fanza"
number_extractor = ["rebd", "oae", "sprl", "higr"]
age_check = { url = "https://www.dmm.co.jp/age_check/=/declared=yes/", target_name = "rurl", target_url = "https://www.dmm.co.jp/top/" }
detail_url = ["https://www.dmm.co.jp/digital/videoa/-/detail/=/cid=", "https://www.dmm.co.jp/mono/dvd/-/detail/=/cid=", "https://www.dmm.co.jp/digital/anime/-/detail/=/cid=", "https://www.dmm.co.jp/mono/anime/-/detail/=/cid=", "https://www.dmm.co.jp/digital/videoc/-/detail/=/cid=", "https://www.dmm.co.jp/digital/nikkatsu/-/detail/=/cid=", "https://www.dmm.co.jp/rental/-/detail/=/cid="]
source_max_userrating = "50"
source_allow_use_site_number = false
expr_number = "//td[contains(text(),'品番：')]/following-sibling::td/text()"
expr_title = "//*[starts-with(@id, 'title')]/text()"
expr_actor_name = '//td[contains(text(),"出演者")]/following-sibling::td/span/a/text()'
expr_actor_photo = ''
expr_studio = "//td[contains(text(),'メーカー')]/following-sibling::td/text()"
expr_runtime = "//td[contains(text(),'収録時間')]/following-sibling::td/text()"
expr_release = "//td[contains(text(),'発売日：')]/following-sibling::td/text()"
expr_outline = "//div[@class='mg-b20 lh4']//p/text()"
expr_director = "//td[contains(text(),'監督：')]/following-sibling::td/text()"
expr_tags = "//td[contains(text(),'ジャンル：')]/following-sibling::td/a/text()"
expr_label = "//td[contains(text(),'レーベル：')]/following-sibling::td/a/text()"
expr_series = "//td[contains(text(),'シリーズ：')]/following-sibling::td/a/text()"
expr_cover = '//div[@class="tx10 pd-3 lh4"]/a/@href'
expr_small_cover = '//div[@class="tx10 pd-3 lh4"]/a/img/@src'
expr_extra_fanart = '//a[@name="sample-image"]/img/@src'
expr_trailer = ""
expr_uncensored = ""
expr_uservotes = ""
expr_userrating = '//*[@id="mu"]/div/table/tbody/tr/td[1]/div[3]/table/tbody/tr[10]/td[2]/img/@src'
replace_number = []
replace_cover = []
replace_extra_fanart = [{ action = "insert", args = ["-", "jp"] }]
replace_actor_photo = []
replace_runtime = [{ action = "replace", args = ["分", ""] }]
replace_release = [{ action = "replace", args = ["/", "-"]}]
replace_userrating = [{action = "substring", args = ["/pc/", ".gif"]}, {action = "replace", args = ["/pc/", ""]}, {action = "replace", args = [".gif", ""]}]
[[sources.fanza.number_pre_handle]]
name = "rebd"
rule = [{ action = "lowercase", args = [] }, { action = "replace", args = ["-", ""] }, { action = "insert", args = ["0", "h_346"] }]
[[sources.fanza.number_pre_handle]]
name = "oae"
rule = [{ action = "lowercase", args = [] }, { action = "replace", args = ["-", ""] }]
[[sources.fanza.number_pre_handle]]
name = "sprl"
rule = [{ action = "lowercase", args = [] }, { action = "replace", args = ["-", ""] }, { action = "insert", args = ["0", "n_1498"] }]
[[sources.fanza.number_pre_handle]]
name = "higr"
rule = [{ action = "lowercase", args = [] }, { action = "replace", args = ["-", ""] }, { action = "insert", args = ["0", "n_1463"] }]

[sources.fc2]
name = "fc2"
number_extractor = ["fc2"]
detail_url = ["https://adult.contents.fc2.com/article/"]
expr_number = '/html/head/title/text()'
expr_title = '//*[@id="top"]/div[1]/section[1]/div/section/div[2]/h3/text()'
expr_actor_name = '//*[@id="top"]/div[1]/section[1]/div/section/div[2]/ul/li[3]/a/text()'
expr_actor_photo = '//*[@id="top"]/div[1]/section[1]/div/section/div[1]/span/img/@src'
expr_studio = '//*[@id="top"]/div[1]/section[1]/div/section/div[2]/ul/li[3]/a/text()'
expr_runtime = "//p[@class='items_article_info']/text()"
expr_release = '//*[@id="top"]/div[1]/section[1]/div/section/div[2]/div[2]/p/text()'
expr_outline = "//div[@class='mg-b20 lh4']//p/text()"
expr_director = '//*[@id="top"]/div[1]/section[1]/div/section/div[2]/ul/li[3]/a/text()'
expr_tags = "//a[@class='tag tagTag']/text()"
expr_label = "//td[contains(text(),'レーベル：')]/following-sibling::td/a/text()"
expr_series = "//td[contains(text(),'シリーズ：')]/following-sibling::td/a/text()"
expr_cover = "//div[@class='items_article_MainitemThumb']/span/img/@src"
expr_small_cover = ''
expr_extra_fanart = '//ul[@class="items_article_SampleImagesArea"]/li/a/@href'
expr_trailer = ""
expr_uncensored = ""
expr_uservotes = '//li[@class="items_article_StarA"]/a/span/text()'
expr_userrating = ""
replace_number = [{ action = "substring", args = ["FC2", ""] }]
replace_cover = [{ action = "insert", args = ["0", "https:"] }]
replace_extra_fanart = []
replace_actor_photo = [{ action = "insert", args = ["0", "https:"] }]
[[sources.fc2.number_pre_handle]]
name = "fc2"
rule = [{ action = "lowercase", args = [] }, { action = "replace", args = ["fc2-ppv-", ""] }, { action = "replace", args = ["fc2-", ""] }, { action = "replace", args = ["fc2ppv ", ""] }, { action = "append", args = ["/"] }]

[sources.nanojav]
name = "nanojav"
number_extractor = ["fc2"]
detail_url = ["https://www.nanojav.com/jav/"]
expr_number = '//div[@class="container"]//h1/a/text()'
expr_title = '//div[@class="container"]//h1/../p[2]/text()'
expr_actor_name = ''
expr_actor_photo = ''
expr_studio = ''
expr_runtime = ''
expr_release = '//*[@id="content"]/div/div/div[2]/div/div/div/div/div[2]/div/p[1]/a/text()'
expr_outline = '//div[@class="container"]//h1/../p[2]/text()'
expr_director = ''
expr_tags = '//div[@class="tags"]/a/text()'
expr_label = ''
expr_series = ''
expr_cover = '//img[@class="cover"]/@src'
expr_small_cover = ''
expr_extra_fanart = '//div[@class="container"]/div[1]/div[1]/div[1]/div[1]/div[2]//*/@src'
expr_trailer = ''
expr_uncensored = ''
expr_uservotes = ''
expr_userrating = ''
replace_number = [{action = "trim", args = []}]
replace_cover = []
replace_extra_fanart = []
replace_actor_photo = []
replace_release = [{action = "trim", args = []}]
replace_tags = [{action = "trim", args = []}]
[[sources.nanojav.number_pre_handle]]
name = "fc2"
rule = [{ action = "lowercase", args = [] }, { action = "replace", args = ["fc2-ppv-", ""] }, { action = "replace", args = ["fc2-", ""] }, { action = "replace", args = ["fc2ppv ", ""] }, { action = "insert", args = ["0","FC2-PPV-"] }]

[sources.javbus]
name = "javbus"
number_extractor = ["heyzo"]
detail_url = ["https://www.javbus.com/"]
expr_number = '//div[@class="container"]/div[1]/div[2]/p[1]/span[2]/text()'
expr_title = '//div[@class="container"]/h3/text()'
expr_actor_name = '//div[@class="star-name"]/a/text()'
expr_actor_photo = '//div[@class="star-name"]/../a/img/@src'
expr_studio = '//span[contains(text(),"製作商:")]/../a/text()'
expr_runtime = '/html/body/div[5]/div[1]/div[2]/p[3]/text()'
expr_release = '/html/body/div[5]/div[1]/div[2]/p[2]/text()'
expr_outline = ''
expr_director = '//span[contains(text(),"導演:")]/../a/text()'
expr_tags = '//span[@class="genre"]/label/a/text()'
expr_label = '//span[contains(text(),"系列:")]/../a/text()'
expr_series = '//span[contains(text(),"系列:")]/../a/text()'
expr_cover = '//a[@class="bigImage"]/@href'
expr_small_cover = ''
expr_extra_fanart = '//div[@id="sample-waterfall"]/a/@href'
expr_trailer = ""
expr_uncensored = '//*[@id="navbar"]/ul[1]/li[@class="active"]/a[contains(@href,"uncensored")]'
expr_uservotes = '//li[@class="items_article_StarA"]/a/span/text()'
expr_userrating = ""
replace_release = [{action = "trim", args = []}]
replace_number = []
replace_cover = [{ action = "insert", args = ["0", "https://www.javbus.com/"] }]
replace_extra_fanart = [{ action = "insert", args = ["0", "https://www.javbus.com/"], when = [{name = "!contains", args = ["https"]}]}]
replace_actor_photo = [{ action = "insert", args = ["0", "https://www.javbus.com/"], when = [{name = "!contains", args = ["https"]}]}]
replace_runtime = [{action = "trim", args = []}, {action = "replace",  args = ["分鐘", ""]}]
[[sources.javbus.number_pre_handle]]
name = "heyzo"
rule = [{ action = "replace", args = [" ", "-"] }]
[[sources.javbus.number_pre_handle]]
name = "rebd"
rule = [{ action = "replace", args = ["REBD-", "REBDB-"] }]

[sources.carib]
name = "carib"
number_extractor = ["carib"]
detail_url = ["https://www.caribbeancom.com/moviepages/"]
expr_number = '/html/head/link[@hreflang="en-US"]/@href'
expr_title = "//div[@class='movie-info section']/div[@class='heading']/h1[@itemprop='name']/text()"
expr_actor_name = "//span[@class='spec-content']/a[@itemprop='actor']/span/text()"
expr_actor_photo = ''
expr_studio = ''
expr_runtime = "//span[@class='spec-content']/span[@itemprop='duration']/text()"
expr_release = "//li[2]/span[@class='spec-content']/text()"
expr_outline = "//div[@class='movie-info section']/p[@itemprop='description']/text()"
expr_director = ''
expr_tags = "//span[@class='spec-content']/a[@itemprop='genre']/text()"
expr_label = "//span[@class='spec-title'][contains(text(),'シリーズ')]/../span[@class='spec-content']/a/text()"
expr_series = "//span[@class='spec-title'][contains(text(),'シリーズ')]/../span[@class='spec-content']/a/text()"
expr_cover = '//div[@class="vjs-poster"]/@style'
expr_small_cover = ''
expr_extra_fanart = "//*[@id='sampleexclude']/div[2]/div/div[@class='grid-item']/div/a/@href"
expr_trailer = ""
expr_uncensored = ''
expr_uservotes = ''
expr_userrating = ""
replace_number = [{ action = "substring", args = ["moviepages/", "/index.html"] }, { action = "replace", args = ["moviepages/", ""] }]
replace_cover = [{ action = "substring", args = ["\"", "\""] }, { action = "insert", args = ["0", "https://www.caribbeancom.com"] }]
replace_extra_fanart = [{ action = "insert", args = ["0", "https://www.caribbeancom.com"] }]
replace_actor_photo = []
[[sources.carib.number_pre_handle]]
name = "carib"
rule = [{ action = "append", args = ["/index.html"] }]

[sources.javdb]
name = "javdb"
number_extractor = ["heyzo"]
age_check = { url = "https://javdb.com/over18?respond=1", target_name = "rurl", target_url = "1j04p8mqknwdh790ds2m6t6d87Zq3f5cd57fq82b9wqzpy4c301b7" }
detail_url = ["https://javdb.com/v/"]
expr_number = '//nav[@class="panel movie-panel-info"]/div[1]/a/@data-clipboard-text'
expr_title = '//strong[@class="current-title"]/text()'
expr_actor_name = '//span[@class="value"]/a[contains(@href,"/actors/")]/text()'
expr_actor_photo = ''
expr_studio = '//span[@class="value"]/a[contains(@href,"/markers/")]/text()'
expr_runtime = '//strong[contains(text(),"時長")]/../span/text()'
expr_release = '//strong[contains(text(),"日期")]/../span/text()'
expr_outline = ""
expr_director = '//strong[contains(text(),"導演")]/../span/text()'
expr_tags = '//strong[contains(text(),"類別")]/../span/a/text()'
expr_label = '//strong[contains(text(),"系列")]/../span/text()'
expr_series = '//strong[contains(text(),"系列")]/../span/text()'
expr_cover = "//div[contains(@class, 'column-video-cover')]/a/img/@src"
expr_small_cover = ''
expr_extra_fanart = "//article[@class='message video-panel']/div[@class='message-body']/div[@class='tile-images preview-images']/a[contains(@href,'/samples/')]/@href"
expr_trailer = '//span[contains(text(),"預告片")]/../../video/source/@src'
expr_uncensored = ''
expr_uservotes = '//span[@class="score-stars"]/../text()'
expr_userrating = '//span[@class="score-stars"]/../text()'
replace_number = []
replace_cover = []
replace_extra_fanart = []
replace_actor_photo = []
[sources.javdb.site_search]
url = "https://javdb.com/search?q="
number_pre_handle = [{ action = "append", args = ["&f=all"] }]
expr_number = '//*[contains(@class,"movie-list")]/div[1]/a/div[contains(@class, "video-title")]/strong/text()'
expr_id = '//*[contains(@class,"movie-list")]/div[1]/a/@href'
number_post_handle = []
id_post_handle = [{ action = "replace", args = ["/v/", ""] }]
[[sources.javdb.number_pre_handle]]
name = "*"
rule = [{ action = "append", args = ["?locale=zh"] }]

[sources.H4610]
name = "H4610"
number_extractor = ["H4610"]
detail_url = ["https://www.h4610.com/moviepages/"]
expr_number = '//div[@id="moviePlayer"]/div/@poster'
expr_title = '//div[@class="moviePlay_title"]/h1/span/text()'
expr_actor_name = ''
expr_actor_photo = ''
expr_studio = ''
expr_runtime = '//div[@id="movieInfo"]/div/div/div/div[2]/section[2]/dl/dd[2]/text()'
expr_release = '//div[@id="movieInfo"]/div/div/div/div[2]/section[2]/dl/dd[5]/text()'
expr_outline = ''
expr_director = ''
expr_tags = ''
expr_label = ''
expr_series = ''
expr_cover = '//div[@id="moviePlayer"]/div/@poster'
expr_small_cover = ''
expr_extra_fanart = ''
expr_trailer = ''
expr_uncensored = ''
expr_uservotes = ''
expr_userrating = ''
replace_number = [{ action = "substring", args = ["/moviepages/", "/images"] }, { action = "replace", args = ["/moviepages/", ""] }]
replace_cover = []
replace_extra_fanart = []
replace_actor_photo = []
[[sources.H4610.number_pre_handle]]
name = "*"
rule = [{ action = "replace", args = ["H4610-", ""] }, { action = "replace", args = ["H4610", ""] }, { action = "append", args = ["/index.html"] }]
