[sources.fanza]
name = "fanza"
source_age_check = { url = "https://www.dmm.co.jp/source_age_check/=/declared=yes/", target_name = "rurl", target_url = "https://www.dmm.co.jp/top/" }
source_detail_url = ["https://www.dmm.co.jp/digital/videoa/-/detail/=/cid=", "https://www.dmm.co.jp/mono/dvd/-/detail/=/cid=", "https://www.dmm.co.jp/digital/anime/-/detail/=/cid=", "https://www.dmm.co.jp/mono/anime/-/detail/=/cid=", "https://www.dmm.co.jp/digital/videoc/-/detail/=/cid=", "https://www.dmm.co.jp/digital/nikkatsu/-/detail/=/cid=", "https://www.dmm.co.jp/rental/-/detail/=/cid="]
source_max_user_rating = "50"
source_allow_use_site_number = false
expr_number = "//td[contains(text(),'品番：')]/following-sibling::td/text()"
expr_title = "//*[starts-with(@id, 'title')]/text()"
expr_actor_name = '//td[contains(text(),"出演者")]/following-sibling::td/span/a/text()'
expr_actor_photo = ''
expr_studio = "//td[contains(text(),'メーカー')]/following-sibling::td/text()"
expr_runtime = "//td[contains(text(),'収録時間')]/following-sibling::td/text()"
expr_release = "//td[contains(text(),'発売日：')]/following-sibling::td/text()"
expr_outline = "//div[@class='mg-b20 lh4']//p/text()"
expr_director = "//td[contains(text(),'監督：')]/following-sibling::td/text()"
expr_tags = "//td[contains(text(),'ジャンル：')]/following-sibling::td/a/text()"
expr_label = "//td[contains(text(),'レーベル：')]/following-sibling::td/a/text()"
expr_series = "//td[contains(text(),'シリーズ：')]/following-sibling::td/a/text()"
expr_cover = '//div[@class="tx10 pd-3 lh4"]/a/@href'
expr_small_cover = '//div[@class="tx10 pd-3 lh4"]/a/img/@src'
expr_extra_fanart = '//a[@name="sample-image"]/img/@src'
expr_trailer = ""
expr_uncensored = ""
expr_user_votes = ""
expr_user_rating = '//*[@id="mu"]/div/table/tbody/tr/td[1]/div[3]/table/tbody/tr[10]/td[2]/img/@src'
replace_number = []
replace_cover = []
replace_extra_fanart = [{ action = "insert", args = ["-", "jp"] }]
replace_actor_photo = []
replace_runtime = [{ action = "replace", args = ["分", ""] }]
replace_release = [{ action = "replace", args = ["/", "-"]}]
replace_user_rating = [{action = "substring", args = ["/pc/", ".gif"]}, {action = "replace", args = ["/pc/", ""]}, {action = "replace", args = [".gif", ""]}]
[[sources.fanza.number_pre_handle]]
name = "rebd"
rule = [{ action = "lowercase", args = [] }, { action = "replace", args = ["-", ""] }, { action = "insert", args = ["0", "h_346"] }]
[[sources.fanza.number_pre_handle]]
name = "oae"
rule = [{ action = "lowercase", args = [] }, { action = "replace", args = ["-", ""] }]
[[sources.fanza.number_pre_handle]]
name = "sprl"
rule = [{ action = "lowercase", args = [] }, { action = "replace", args = ["-", ""] }, { action = "insert", args = ["0", "n_1498"] }]
[[sources.fanza.number_pre_handle]]
name = "higr"
rule = [{ action = "lowercase", args = [] }, { action = "replace", args = ["-", ""] }, { action = "insert", args = ["0", "n_1463"] }]
