
[sources.javbus]
name = "javbus"
source_detail_url = ["https://www.javbus.com/"]
expr_number = '//div[@class="container"]/div[1]/div[2]/p[1]/span[2]/text()'
expr_title = '//div[@class="container"]/h3/text()'
expr_actor_name = '//div[@class="star-name"]/a/text()'
expr_actor_photo = '//div[@class="star-name"]/../a/img/@src'
expr_studio = '//span[contains(text(),"製作商:")]/../a/text()'
expr_runtime = '/html/body/div[5]/div[1]/div[2]/p[3]/text()'
expr_release = '/html/body/div[5]/div[1]/div[2]/p[2]/text()'
expr_outline = ''
expr_director = '//span[contains(text(),"導演:")]/../a/text()'
expr_tags = '//span[@class="genre"]/label/a/text()'
expr_label = '//span[contains(text(),"系列:")]/../a/text()'
expr_series = '//span[contains(text(),"系列:")]/../a/text()'
expr_cover = '//a[@class="bigImage"]/@href'
expr_small_cover = ''
expr_extra_fanart = '//div[@id="sample-waterfall"]/a/@href'
expr_trailer = ""
expr_uncensored = '//*[@id="navbar"]/ul[1]/li[@class="active"]/a[contains(@href,"uncensored")]'
expr_user_votes = '//li[@class="items_article_StarA"]/a/span/text()'
expr_user_rating = ''
replace_release = [{action = "trim", args = []}]
replace_number = []
replace_cover = [{ action = "insert", args = ["0", "https://www.javbus.com/"] }]
replace_extra_fanart = [{ action = "insert", args = ["0", "https://www.javbus.com/"], when = [{name = "!contains", args = ["https"]}]}]
replace_actor_photo = [{ action = "insert", args = ["0", "https://www.javbus.com/"], when = [{name = "!contains", args = ["https"]}]}]
replace_runtime = [{action = "trim", args = []}, {action = "replace",  args = ["分鐘", ""]}]
[[sources.javbus.number_pre_handle]]
name = "heyzo"
rule = [{ action = "replace", args = [" ", "-"] }]
[[sources.javbus.number_pre_handle]]
name = "rebd"
rule = [{ action = "replace", args = ["REBD-", "REBDB-"] }]
