[sources.javdb]
name = "javdb"
source_age_check = { url = "https://javdb.com/over18?respond=1", target_name = "rurl", target_url = "1j04p8mqknwdh790ds2m6t6d87Zq3f5cd57fq82b9wqzpy4c301b7" }
source_detail_url = ["https://javdb.com/v/"]
source_max_user_rating = "5"
expr_number = '//nav[@class="panel movie-panel-info"]/div[1]/a/@data-clipboard-text'
expr_title = '//strong[@class="current-title"]/text()'
expr_actor_name = '//span[@class="value"]/a[contains(@href,"/actors/")]/text()'
expr_actor_photo = ''
expr_studio = '//span[@class="value"]/a[contains(@href,"/markers/")]/text()'
expr_runtime = '//strong[contains(text(),"時長")]/../span/text()'
expr_release = '//strong[contains(text(),"日期")]/../span/text()'
expr_outline = ""
expr_director = '//strong[contains(text(),"導演")]/../span/text()'
expr_tags = '//strong[contains(text(),"類別")]/../span/a/text()'
expr_label = '//strong[contains(text(),"系列")]/../span/text()'
expr_series = '//strong[contains(text(),"系列")]/../span/text()'
expr_cover = "//div[contains(@class, 'column-video-cover')]/a/img/@src"
expr_small_cover = ''
expr_extra_fanart = "//article[@class='message video-panel']/div[@class='message-body']/div[@class='tile-images preview-images']/a[contains(@href,'/samples/')]/@href"
expr_trailer = '//span[contains(text(),"預告片")]/../../video/source/@src'
expr_uncensored = ''
expr_uservotes = '//span[@class="score-stars"]/../text()'
expr_userrating = '//span[@class="score-stars"]/../text()'
replace_number = []
replace_cover = []
replace_extra_fanart = []
replace_actor_photo = []
replace_runtime = [{action = "replace", args = ["分鍾", ""]}, {action = "trim", args = []}]
replace_userrating = [{action = "trim", args = []}, {action = "substring", args = ["0", "分"]}]
replace_uservotes = [{action = "substring", args = ["由", "人"]}, {action = "replace", args = ["由", ""]}]
[sources.javdb.site_search]
url = "https://javdb.com/search?q="
site_number_pre_handle = [{ action = "append", args = ["&f=all"] }]
expr_number = '//*[contains(@class,"movie-list")]/div[1]/a/div[contains(@class, "video-title")]/strong/text()'
expr_id = '//*[contains(@class,"movie-list")]/div[1]/a/@href'
site_number_post_handle = []
site_id_post_handle = [{ action = "replace", args = ["/v/", ""] }]
[[sources.javdb.number_pre_handle]]
name = "*"
rule = [{ action = "append", args = ["?locale=zh"] }]
