[[sources.missav.number_pre_handle]]
name = "fc2"
rule = [{ action = "lowercase", args = [] }, { action = "replace", args = ["fc2-ppv-", ""] }, { action = "replace", args = ["fc2-", ""] }, { action = "replace", args = ["fc2ppv ", ""] }, { action = "insert", args = ["0","fc2-ppv-"] }]

[sources.missav]
name = "missav"
source_detail_url = ["https://missav.com/cn/"]
source_max_user_rating = ""
source_allow_use_site_number = true
expr_number = '//span[contains(text(),"番号:")]/following-sibling::span/text()'
expr_title = '//span[contains(text(),"标题:")]/following-sibling::span/text()'
expr_actor_name = '//span[contains(text(),"类型:")]/following-sibling::a/text()'
expr_actor_photo = ''
expr_studio = ''
expr_runtime = ''
expr_release = '//span[contains(text(),"发行日期:")]/following-sibling::span/text()'
expr_outline = '//h1[1]/text()'
expr_director = ''
expr_tags = '//span[contains(text(),"标籤:")]/following-sibling::a/text()'
expr_label = ''
expr_series = ''
expr_cover = '//video[1]/@data-poster'
expr_small_cover = ''
expr_extra_fanart = ''
expr_trailer = ""
expr_uncensored = ""
expr_user_rating = ''
expr_user_votes = ''
replace_number = []
replace_title = []
replace_outline = []
replace_studio = []
replace_director = []
replace_cover = []
replace_small_cover = []
replace_extra_fanart = []
replace_actor_photo = []
replace_runtime = []
replace_release = []
replace_tags = []
replace_label = []
replace_series = []
replace_user_rating = []
replace_user_votes = []

