[sources.nanojav]
name = "nanojav"
source_detail_url = ["https://www.nanojav.com/jav/"]
expr_number = '//div[@class="container"]//h1/a/text()'
expr_title = '//div[@class="container"]//h1/../p[2]/text()'
expr_actor_name = ''
expr_actor_photo = ''
expr_studio = ''
expr_runtime = ''
expr_release = '//*[@id="content"]/div/div/div[2]/div/div/div/div/div[2]/div/p[1]/a/text()'
expr_outline = '//div[@class="container"]//h1/../p[2]/text()'
expr_director = ''
expr_tags = '//div[@class="tags"]/a/text()'
expr_label = ''
expr_series = ''
expr_cover = '//img[@class="cover"]/@src'
expr_small_cover = ''
expr_extra_fanart = '//div[@class="container"]/div[1]/div[1]/div[1]/div[1]/div[2]//*/@src'
expr_trailer = ''
expr_uncensored = ''
expr_user_votes = ''
expr_user_rating = ''
replace_number = [{action = "trim", args = []}]
replace_cover = []
replace_extra_fanart = []
replace_actor_photo = []
replace_release = [{action = "trim", args = []}]
replace_tags = [{action = "trim", args = []}]
[[sources.nanojav.number_pre_handle]]
name = "fc2"
rule = [{ action = "lowercase", args = [] }, { action = "replace", args = ["fc2-ppv-", ""] }, { action = "replace", args = ["fc2-", ""] }, { action = "replace", args = ["fc2ppv ", ""] }, { action = "insert", args = ["0","FC2-PPV-"] }]
